# Generated by Django 5.2.2 on 2026-04-08 20:00

import app.models
import app.utils.validation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_data_file', models.FileField(storage=app.models.OverwriteStorage(), upload_to='group/', validators=[app.utils.validation.validate_group_file_extension])),
                ('num_entries', models.PositiveIntegerField(default=0)),
                ('num_groups', models.PositiveIntegerField(default=0)),
                ('grouping', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_data_file', models.FileField(storage=app.models.OverwriteStorage(), upload_to='rawdata/', validators=[app.utils.validation.validate_rawdata_file_extension])),
                ('num_entries', models.PositiveIntegerField(default=0)),
                ('spec_data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filteroption', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('number', 'Number')], max_length=12)),
                ('applyin', models.CharField(blank=True, choices=[('inTotal', 'In Total'), ('inEach', 'In Each'), ('inEither', 'In Either')], max_length=10)),
                ('value', models.PositiveIntegerField(null=True)),
                ('filter_data', models.JSONField(null=True)),
                ('grouping', models.JSONField(null=True)),
                ('num_entries', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.groupdataupload')),
                ('raw_file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rawdataupload')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalize_data', models.JSONField(null=True)),
                ('grouping', models.JSONField(null=True)),
                ('num_entries', models.PositiveIntegerField(default=0)),
                ('method', models.CharField(blank=True, choices=[('reference', 'Reference'), ('divide', 'Divide'), ('subtract', 'Subtract'), ('z-score', 'Z-Score')], max_length=20, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('statistic', models.CharField(blank=True, choices=[('mean', 'Mean'), ('median', 'Median'), ('mode', 'Mode')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filter_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.filterdata')),
            ],
        ),
        migrations.CreateModel(
            name='TransformedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transform_data', models.JSONField(null=True)),
                ('grouping', models.JSONField(null=True)),
                ('num_entries', models.PositiveIntegerField(default=0)),
                ('epsilon', models.FloatField(blank=True, help_text='Epsilon value for log2 transformation. Must be set before transformation.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.normalizeddata')),
            ],
        ),
        migrations.CreateModel(
            name='ImputeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impute_data', models.JSONField(null=True)),
                ('grouping', models.JSONField(null=True)),
                ('num_entries', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trans', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.transformeddata')),
            ],
        ),
        migrations.CreateModel(
            name='TtestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_data', models.JSONField(null=True)),
                ('reference_group', models.CharField(blank=True, max_length=100, null=True)),
                ('num_proteins', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impute_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.imputedata')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
                ('filtered_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.filterdata')),
                ('group_file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.groupdataupload')),
                ('impute_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.imputedata')),
                ('normal_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.normalizeddata')),
                ('raw_file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rawdataupload')),
                ('transformed_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.transformeddata')),
                ('ttest_results', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ttestresults')),
            ],
        ),
    ]
